###############################################################
#
#  DIDComm Load Balancer
#
###############################################################
inbound:
  host: 0.0.0.0
  httpPort: 9003
  wsPort: 9001
  external: "ws://172.17.0.1:9001"

###############################################################
#
#  AMQP Server (rabbitMQ)
#
###############################################################
amqp:
  user: canis
  password: canis
  host: 172.17.0.1
  port: 5672
  vhost: canis

###############################################################
#
#  Datastore configuration
#
###############################################################
datastore:
  database: mongo
  mongo:
    url: "mongodb://172.17.0.1:27017"
    database: "canis"

###############################################################
#
#  GRPC Server
#
###############################################################
loadbalancer:
  grpc:
    host: 0.0.0.0
    port: 9996

###############################################################
#
#  Ledger-store configuration
#
###############################################################
ledgerstore:
  database: couchdb
  couchdb:
    url: "localhost:5984"