apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "canis.fullname" . }}-aries-agent-rest
  labels:
    name: {{ include "canis.fullname" . }}-aries-agent-rest
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ include "canis.fullname" . }}-aries-agent-rest
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ include "canis.fullname" . }}-aries-agent-rest
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "canis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - image: "{{ .Values.ariesAgentRest.repository }}:{{ .Values.ariesAgentRest.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          name: aries-agent-rest
          command:
            - "aries-agent-rest"
            - "start"
            - "--api-host"
            - "0.0.0.0:{{ .Values.ariesAgentRest.api.port }}"
            - "--database-prefix"
            - "mobile-agent"
            - "--database-type"
            - "mem"
            - "--webhook-url"
            - ""
            - "--http-resolver-url"
            - "sov@http://http-indy-resolver:{{ .Values.httpIndyResolver.http.port }}/did"
            - "--outbound-transport"
            - "ws"
            - "--outbound-transport"
            - "http"
            - "--inbound-host"
            - "http@0.0.0.0:{{ .Values.ariesAgentRest.http.port }}"
            - "--inbound-host-external"
            {{if eq .Values.ariesAgentRest.external.type "loadbalancer"}}
            - "http@http://{{ .Values.ariesAgentRest.external.loadbalancer.host}}:{{ .Values.ariesAgentRest.http.port }}"
            {{ else }}
            - "http@http://{{ .Values.ariesAgentRest.external.nodePort.host }}:{{ .Values.ariesAgentRest.external.nodePort.httpPort }}"
            {{ end }}
            - "--log-level"
            - "DEBUG"
          ports:
            - name: api
              containerPort: {{ .Values.ariesAgentRest.api.port }}
              protocol: TCP
            - name: http
              containerPort: {{ .Values.ariesAgentRest.http.port }}
              protocol: TCP
          resources: {}
          volumeMounts:
            - mountPath: "/etc/canis/common"
              name: common-config
      restartPolicy: Always
      volumes:
        - name: common-config
          configMap:
            name: {{ include "canis.fullname" . }}-common-config
